name: Build

on:
  push:
    branches: [master]
  pull_request:
  release:
    types: [created]

jobs:
 build-linux:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl build-essential pkg-config libssl-dev dpkg-dev
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          . $HOME/.cargo/env
      - name: Build binary
        run: |
           . $HOME/.cargo/env
           cargo build --release
      - name: Create .deb package
        run: |
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/local/bin
          cp target/release/img2stl pkg/usr/local/bin/
          dpkg-deb --build pkg img2stl.deb
      - name: Strip and generate standalone binary
        run: |
          apt install -y strip-nondeterminism
          strip target/release/img2stl
          cp target/release/img2stl img2stl

      - name: Upload DEB file
        uses: actions/upload-artifact@v4
        with:
          name: debian-artifacts
          path: |
            img2stl
            img2stl.deb
      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            img2stl
            img2stl.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

 build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build exe
        run: cargo build --release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-artifacts
          path: target/release/img2stl.exe

      - name: Upload to release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v2
        with:
          files: |
            target/release/img2stl.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
