name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
 build-linux:
    runs-on: ubuntu-latest
    container:
      image: debian:bullseye
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          apt install -y curl build-essential pkg-config libssl-dev dpkg-dev
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
      - name: Build binary
        run: cargo build --release
      - name: Create .deb package
        run: |
          mkdir -p pkg/DEBIAN
          mkdir -p pkg/usr/local/bin
          cp target/release/img2stl pkg/usr/local/bin/
          dpkg-deb --build pkg img2stl.deb

      - name: Upload DEB file
        uses: actions/upload-artifact@v3
        with:
          name: debian-artifacts
          path: |
            target/release/img2stl
            img2stl.deb

 build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build exe
        run: cargo build --release
      - uses: actions/upload-artifact@v3
        with:
          name: windows-artifacts
          path: target/release/img2stl.exe
